plugins {
	id 'java'
	id 'com.diffplug.eclipse.apt' version '4.3.0'
  	id 'eclipse'
}

group = 'com.tlback'
version = '0.0.1-SNAPSHOT'

subprojects {
    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}

// Develop configs
task generateEclipseConfig {
  	dependsOn ':tl-core:generateJooq', 'eclipse', 'eclipseJdt', 'eclipseJdtApt'
}

eclipse {
   	project {
    	name = rootProject.name
  }
  jdt {
	file {
      	withProperties { props ->
        	props['org.eclipse.jdt.core.compiler.codegen.methodParameters'] = 'generate'
      	}
    }
    apt {
      		genSrcDir = 'build/generated/sources/annotationProcessor/java/main'
      		genTestSrcDir = 'build/generated/sources/annotationProcessor/java/test'
      		reconcileEnabled = true
    	}
  	}
  	synchronizationTasks generateEclipseConfig
}

