plugins {
	id 'java'
	id 'application'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'nu.studer.jooq' version '9.0'
	id 'org.liquibase.gradle' version '2.2.2'
}

def jooqVer = '3.19.16'
def mapstructVer = '1.6.3'
def liquibaseVer = '4.17.0'
def snakeYmlVer = '1.33'

group = 'com.tlback'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// exclude swagger annotation and use newer version due conflicts with avro serializer
	implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0") {
	    exclude group: "io.swagger.core.v3", module:"swagger-annotations"
	}
	implementation 'io.swagger.core.v3:swagger-annotations:2.2.15'

	// utils
	implementation "org.mapstruct:mapstruct:${mapstructVer}"
	annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVer}"
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
	// ---

	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.testcontainers:junit-jupiter'

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// reactive stack w jooq
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
	implementation 'org.postgresql:r2dbc-postgresql'
	runtimeOnly 'org.postgresql:postgresql'

	jooqGenerator "org.yaml:snakeyaml:${snakeYmlVer}"
    jooqGenerator "org.jooq:jooq-meta-extensions-liquibase:${jooqVer}"
    jooqGenerator "org.liquibase:liquibase-core:${liquibaseVer}"
	// ---

	// liquibase
	liquibaseRuntime "org.liquibase:liquibase-core:${liquibaseVer}"
    liquibaseRuntime 'org.liquibase:liquibase-groovy-dsl:3.0.0'
    liquibaseRuntime 'info.picocli:picocli:4.6.1'
    liquibaseRuntime 'org.postgresql:postgresql:42.3.6'
    liquibaseRuntime "org.yaml:snakeyaml:${snakeYmlVer}"
	// ---

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

def db_host = System.getenv('DB_HOST')
def db_port = System.getenv('DB_PORT')
def db_user = System.getenv('DB_USER')
def db_pass = System.getenv('DB_PASSWORD')
def db_name = System.getenv('DB_NAME')

def psql_url = "jdbc:postgresql://${db_host}:${db_port}/${db_name}?currentSchema=public"
def psql_pswrd = "${db_pass}"
def psql_user = "${db_user}"

def liquibaseRoot = "${project.projectDir}/src/main/resources/db/changelog"
def changelogFile = 'changelog-master.yml'

liquibase {
    activities {
        main {
            classpath liquibaseRoot
            changeLogFile changelogFile
            url psql_url
            username psql_user
            password psql_pswrd
        }
    }
}

jooq {
 	version "${jooqVer}"
	configurations {
		main {
			generationTool {
 		        generator {
 		            database {
 		                name = 'org.jooq.meta.extensions.liquibase.LiquibaseDatabase'
						inputSchema = 'PUBLIC'

 		                properties {

							property {
        						key = "rootPath"
        					  	value = liquibaseRoot
        					}

        					property {
        					  	key = "scripts"
        					  	value = changelogFile
        					}
 		                }
 		            }
 		            target {
 		                packageName = 'com.tlback.jooq.gen'
 		                directory = 'build/generated-src/jooq'
 		            }
 		        }
 		    }
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
