plugins {
	id 'java'
	id 'application'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'nu.studer.jooq' version '9.0'
	id 'org.liquibase.gradle' version '2.2.2'
}

def jooq_version = '3.19.16'
def mapstructVer = '1.6.3'
def liquibaseVer = '3.5.5'

group = 'com.tlback'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// exclude swagger annotation and use newer version due conflicts with avro serializer
	implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0"){
	    exclude group: "io.swagger.core.v3", module:"swagger-annotations"
	}
	implementation 'io.swagger.core.v3:swagger-annotations:2.2.15'

	// utils
	implementation "org.mapstruct:mapstruct:${mapstructVer}"
	annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVer}"
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
	// ---

	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.testcontainers:junit-jupiter'

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// reactive stack w jooq
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
	implementation 'org.postgresql:r2dbc-postgresql'
	runtimeOnly 'org.postgresql:postgresql'
	implementation "org.jooq:jooq:${jooq_version}"
	implementation "org.jooq:jooq-meta-extensions:${jooq_version}"
	jooqGenerator 'org.postgresql:postgresql'
	// ---

	// liquibase
	liquibaseRuntime group: 'org.liquibase', name: 'liquibase-core', version: '3.5.1'
    liquibaseRuntime 'org.liquibase:liquibase-groovy-dsl:3.0.0'
    liquibaseRuntime 'info.picocli:picocli:4.6.1'
    liquibaseRuntime 'org.postgresql:postgresql:42.3.6'
    liquibaseRuntime group: 'org.yaml', name: 'snakeyaml', version: '1.30'
	// ---

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

def psql_url = 'jdbc:postgresql://localhost:5599/tl_back?currentSchema=public'
def psql_pswrd = 'postgres'
def psql_user = 'postgres'

liquibase {
    activities {
        main {
            classpath "${project.projectDir}/src/main/resources/db/"
            changeLogFile "changelog/changelog-master.yml"
            url psql_url
            username psql_user
            password psql_pswrd
        }
    }
}

jooq {
 	version "${jooq_version}"
	configurations {
		main {
			generationTool {
 		        jdbc {
 		            driver = 'org.postgresql.Driver'
 		            url = "${psql_url}"
 		            user = "${psql_user}"
 		            password =  "${psql_pswrd}"
 		        }

 		        generator {
 		            name = 'org.jooq.codegen.DefaultGenerator'
 		            database {
 		                name = 'org.jooq.meta.postgres.PostgresDatabase'
 		                inputSchema = 'public' // Схема для генерации классов
 		            }
 		            target {
 		                packageName = 'com.tlback.jooq.gen' 
 		                directory = 'build/generated-src/jooq'
 		            }
 		        }
 		   }
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
