server:
  port: ${TL_SERVER_PORT:8095}

spring:
  webflux.base-path: /api
  data:
    redis:
      host: ${TL_REDIS_HOST:localhost}
      port: ${TL_REDIS_PORT:6379}
  r2dbc:
    url: r2dbc:postgresql://${TL_DB_HOST:localhost}:${TL_DB_PORT:5599}/${TL_DB_NAME:tldb}
    username: ${TL_DB_USER:postgres}
    password: ${TL_DB_PASSWORD:postgres}

app:
  baseUrl: https://tl.ow-pk.ru/api

springdoc:
  api-docs.enabled: true
  swagger-ui:
    path: /swagger