server:
  port: 8095

swagger.url: "${SWAGGER_URL:http://localhost:8095}"

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5599/tl_back
    username: postgres
    password: postgres

springdoc.api-docs.enabled: true