plugins {
	id 'application'
	id 'nu.studer.jooq' version '9.0'
	id 'org.liquibase.gradle' version '2.2.2'

    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

def jooqVer = '3.19.1'
def mapstructVer = '1.6.3'
def liquibaseVer = '4.17.0'
def snakeYmlVer = '1.33'

dependencies {
	// utils
	implementation "org.mapstruct:mapstruct:${mapstructVer}"
	annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVer}"
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
	// ---

	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// reactive stack w jooq
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.3.0'
	implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
	implementation 'org.springframework.boot:spring-boot-starter-jooq'
	implementation 'org.postgresql:r2dbc-postgresql'
	runtimeOnly 'org.postgresql:postgresql'

	jooqGenerator "org.yaml:snakeyaml:${snakeYmlVer}"
    jooqGenerator "org.jooq:jooq-meta-extensions-liquibase:${jooqVer}"
    jooqGenerator "org.liquibase:liquibase-core:${liquibaseVer}"
	// ---

	// liquibase
	liquibaseRuntime "org.liquibase:liquibase-core:${liquibaseVer}"
    liquibaseRuntime 'org.liquibase:liquibase-groovy-dsl:3.0.0'
    liquibaseRuntime 'info.picocli:picocli:4.6.1'
    liquibaseRuntime 'org.postgresql:postgresql:42.3.6'
    liquibaseRuntime "org.yaml:snakeyaml:${snakeYmlVer}"
	// ---

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.testcontainers:junit-jupiter'
	testImplementation 'io.projectreactor:reactor-test:3.7.6'

	runtimeOnly 'io.netty:netty-resolver-dns-native-macos:4.2.2.Final:osx-aarch_64'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.2'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

def db_host = System.getenv('TL_DB_HOST')
def db_port = System.getenv('TL_DB_PORT')
def db_user = System.getenv('TL_DB_USER')
def db_pass = System.getenv('TL_DB_PASSWORD')
def db_name = System.getenv('TL_DB_NAME')

def psql_url = "jdbc:postgresql://${db_host}:${db_port}/${db_name}?currentSchema=public"
def psql_pswrd = "${db_pass}"
def psql_user = "${db_user}"

def liquibaseRoot = "${project.projectDir}/src/main/resources/db/changelog"
def changelogFile = 'changelog-master.yml'

liquibase {
    activities {
        main {
            classpath liquibaseRoot
            changeLogFile changelogFile
            url psql_url
            username psql_user
            password psql_pswrd
        }
    }
}

jooq {
 	version "${jooqVer}"
	configurations {
		main {
			generationTool {
 		        generator {
 		            database {
 		                name = 'org.jooq.meta.extensions.liquibase.LiquibaseDatabase'
						inputSchema = 'PUBLIC'

 		                properties {

							property {
        						key = "rootPath"
        					  	value = liquibaseRoot
        					}

        					property {
        					  	key = "scripts"
        					  	value = changelogFile
        					}
 		                }
 		            }
 		            target {
 		                packageName = 'com.tlback.jooq.gen'
 		                directory = 'build/generated-src/jooq'
 		            }
 		        }
 		    }
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

bootJar {
	mainClassName = 'com.tlback.core.TlbackApplication'
}
