services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: tl_backend
    ports:
      - "8095:8095"
    environment:
      - SWAGGER_URL=https://owpk.ru
      - TL_DB_HOST=db
      - TL_DB_PORT=5432
      - TL_DB_USER=${TL_DB_USER:-postgres}
      - TL_DB_PASSWORD=${TL_DB_PASSWORD:-postgres}
      - TL_DB_NAME=${TL_DB_NAME:-tl_back}
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: postgres:17
    container_name: tl_db
    environment:
      - POSTGRES_DB=${TL_DB_NAME:-tl_back}
      - POSTGRES_USER=${TL_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${TL_DB_PASSWORD:-postgres}
    ports:
      - 5599:5432
    networks:
      - backend_network

networks:
  backend_network:
